import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ImageLink from './components/ImageLink';
import PageHeader from './components/PageHeader';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <PageHeader />
          <ImageLink
            pageTarget="/courses"
            src="https://img.icons8.com/ios7/512/FFFFFF/settings.png"
            alt="Settings"
          />

          <ImageLink pageTarget="/courses" src="/inbox.png" alt="Inbox" />
        </header>
        {children}
      </body>
    </html>
  );
}
